# widgets events
# https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Events.html
# ipysheet
# https://coderzcolumn.com/tutorials/python/interactive-spreadsheet-in-jupyter-notebook-using-ipysheet

def spreadsheet_inp():
    
    from IPython.display import display
    import ipywidgets as widgets
    import pandas as pd
    import numpy as np
    import ipysheet
    from datetime import datetime
    
    # df prep
    df = pd.DataFrame({
        "col1": ["a"]*3 + ["b"]*3,
        "col2": np.random.rand(6)
    })

    sh = ipysheet.from_dataframe(df)

    # ui prep
    button = widgets.Button(description="Calculate!")
    output = widgets.Output()

    display(sh, button, output)

    def on_button_clicked(b):

        df = ipysheet.to_dataframe(sh)
        df.col2 = df.col2*-10 

        with output:
            print(str(datetime.now().strftime("%H:%M:%S")) + " This is output generated by clicking on the button. It multiplies col2 by -10.")
            display(ipysheet.from_dataframe(df))

    button.on_click(on_button_clicked)
    
